### PR TITLE
:bug: Handle file writing errors as fatal errors

### LINKED ISSUE #314: Handle error writing the output file
Right now, we ignore the error https://github.com/konveyor/analyzer-lsp/blob/90359e663aa9655450a6feda2db2a7fcd10475e5/cmd/analyzer/main.go#L216

We should treat this as a fatal error

### PR DESCRIPTION
**Pull request by sarthaksarthak9**
Closes #314

### CODE REVIEW

**Comment by sarthaksarthak9** [comment]
@pranavgaikwad how to run test locally?

**Comment by sarthaksarthak9** [comment]
> @sarthaksarthak9 `make ci` target is not defined in the Dockerfile. You will have to run the demo docker to test locally. https://github.com/konveyor/analyzer-lsp/#quick-demo

Thank you!!

**Comment by shawn-hurley** [comment]
@sarthaksarthak9 I think I fixed the build, I am really sorry things should be looking better now

**Comment by sarthaksarthak9** [comment]
> @sarthaksarthak9 I think I fixed the build, I am really sorry things should be looking better now

thank you !!

**Review by pranavgaikwad — APPROVED** [review]

**Pull request merged**
