### PR TITLE
:bug: copy the custom plugin to m2

### PR DESCRIPTION
**Pull request by pranavgaikwad**
API Tests PR: 55

Sorry, `install-file` ended up failing because it wasn't resolving the plugin deps correctly and was creating artifact without full classpath.

### CODE REVIEW

**Review by fabianvf — COMMENTED** [review]
Not that familiar with what this is actually doing, but the code itself looks sane

**Comment by shawn-hurley** [comment]
Why this over installing with `mvn install-file -s settings.xml` using the settings?

**Comment by pranavgaikwad** [comment]
@shawn-hurley install goal didnt work. I was seeing errors with classpath when running. I saw that there are additional metadata files with the plugin that weren't present when I do the install.

**Review by shawn-hurley — APPROVED** [review]

**Comment by pranavgaikwad** [comment]
This is no longer needed as we are using the other plugin now

**Pull request closed without merging**
