### PR TITLE
:sparkles: Get deps fallback for .war/.ear files if no jars found

### PR DESCRIPTION
**Pull request by eemcmullan**

### CODE REVIEW

**Review by aufi — APPROVED** [review]
LGTM

**Comment by jmle** [comment]
The only problem here is the case when there are multiple poms inside the WAR file, which is something that can happen. In that case, this solution would give a partial list of dependencies, since we are stopping after finding the first pom. Ideally we would find all poms and concat their respective deps

**Comment by pranavgaikwad** [comment]
@jmle What happens in cases where the POMs have a parent - child relation? Does the fallback parser care if it cannot fully resolve the parent or children modules?

**Comment by eemcmullan** [comment]
@jmle updated to get all poms

**Review by pranavgaikwad — APPROVED** [review]

**Pull request merged**
