### PR TITLE
:sparkles: add new category

### PR DESCRIPTION
**Pull request by pranavgaikwad**

### CODE REVIEW

**Comment by shawn-hurley** [comment]
what is the difference between potential and optional?

**Comment by pranavgaikwad** [comment]
@shawn-hurley so this is a category for violations that found a match for a certain condition but couldn't generate valid output (this is one example I found in windup report, there could be more) . For instance, an XML condition matched in an OR caused as a result of `builtin.xml` but the file was malformed and a valid violation couldn't be created for condition that followed `builtin.xml`

**Comment by shawn-hurley** [comment]
I wonder if this is a second set of things that are errors? we already need to add a "ran but didn't find any issues" rules as well

**Comment by pranavgaikwad** [comment]
@shawn-hurley makes sense to me. lets close this PR for now, I'll follow up with an issue instead

**Pull request closed without merging**
