### PR TITLE
:sparkles: Update logging of closed RPC errors

### PR DESCRIPTION
**Pull request by abrugaro**
Solves https://github.com/konveyor/analyzer-lsp/issues/500

### CODE REVIEW

**Comment by abrugaro** [comment]
Thanks for your comment @shawn-hurley 

In the `call` method, should I add it here: https://github.com/konveyor/analyzer-lsp/blob/main/jsonrpc2_v2/conn.go#L354 ? and here for `Notify`: https://github.com/konveyor/analyzer-lsp/blob/main/jsonrpc2_v2/conn.go#L288?


And one more question, should I do the same for the jsonrpc2 (v1) package?

**Comment by shawn-hurley** [comment]
Yes those locations look correct to me

and yes if you can add it in v1 as well that would be amazing

**Comment by shawn-hurley** [comment]
@abrugaro, we are experiencing some issues with the CI system, so while this is a low-risk change that I would normally merge on green, this might take a little longer to get in. I am sorry

**Comment by abrugaro** [comment]
> @abrugaro, we are experiencing some issues with the CI system, so while this is a low-risk change that I would normally merge on green, this might take a little longer to get in. I am sorry

Sure, its my first contribution to this project so I prefer to wait to be sure that everything is ok before merging :smile:

**Comment by shawn-hurley** [comment]
Thank you @abrugaro this is a really helpful change!

**Pull request merged**
