### PR TITLE
:bug: log yaml parsing errors when parsing rules

### LINKED ISSUE #476: Log yaml parsing errors when parsing rules from a file
This will be useful to find issues with bad YAML files without going unnoticed like one I found here https://github.com/konveyor/rulesets/pull/58

Add log.Error(err, ...) here:

https://github.com/konveyor/analyzer-lsp/blob/01d07083f8033531ca1666b899329ed47cb8ad24/parser/rule_parser.go#L94
https://github.com/konveyor/analyzer-lsp/blob/01d07083f8033531ca1666b899329ed47cb8ad24/parser/rule_parser.go#L183

### PR DESCRIPTION
**Pull request by Vickysomtee**
fixes #476

### CODE REVIEW

**Review by shawn-hurley — CHANGES_REQUESTED** [review]
This is awesome! Thank you for taking the time to submit this PR!

I think that this is ready to go once we keep the err coming from `yam.Unmarshal`.

**Comment by Vickysomtee** [comment]
@shawn-hurley updated the PR

**Review by shawn-hurley — APPROVED** [review]

**Review by djzager — APPROVED** [review]

**Comment by eemcmullan** [comment]
+1 also to returning the err from unmarshal(). Otherwise LGTM

**Review by eemcmullan — APPROVED** [review]

**Comment by shawn-hurley** [comment]
Thank you so much for the fix @Vickysomtee! this is really helpful!

**Pull request merged**
