### PR TITLE
:bug: Update go mod in generic external provider

### LINKED ISSUE #325: Go mod file in generic external provider has unnecessary replace directive
This is making the builds fail. I think this is unnecessary https://github.com/konveyor/analyzer-lsp/blob/main/external-providers/generic-external-provider/go.mod#L42

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Fixes #325

### CODE REVIEW

**Review by jmontleon — APPROVED** [review]
/LGTM

**Comment by shawn-hurley** [comment]
Looks like this is blowing up the dependencies in the demo the change looks fine, but we probably need to dig into that

**Comment by pranavgaikwad** [comment]
yeah, investigating now.

**Comment by pranavgaikwad** [comment]
@shawn-hurley this breakage is random, and has nothing to do with change in this PR. Actually, the dep is broken in the base image, we can't find `go` binary somehow. Check this failure that happened after merging your old PR https://github.com/konveyor/analyzer-lsp/actions/runs/6148484915/job/16682284146

**Comment by jmontleon** [comment]
It's my fault, overzealous cleanup. https://github.com/konveyor/java-analyzer-bundle/pull/66/files

**Pull request merged**
