### PR TITLE
:seedling: Add Dockerfile for debugging

### PR DESCRIPTION
**Pull request by jmle**

### CODE REVIEW

**Review by pranavgaikwad — CHANGES_REQUESTED** [review]
Can you please add a doc that explains usage of this? and perhaps, move this into hack/ directory or something?

**Comment by jmle** [comment]
@pranavgaikwad do you think it would make sense to have a `docker` directory with all the different docker images?

**Comment by pranavgaikwad** [comment]
@jmle We have the release automation working off of the ./Dockerfile. It's good to have the default ones in the root path I think.

**Comment by jmle** [comment]
@pranavgaikwad moved to `debug` and provided a README

**Comment by jmle** [comment]
@pranavgaikwad I added the requested changes - I think this can be useful, especially for people starting with the project

**Pull request merged**
